sudo: false
dist: trusty
language: java

jdk:
  - oraclejdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - sanyakovlev@yandex.ru
    on_success: never
    on_failure: always