CREATE DATABASE dbstore;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  login CHARACTER VARYING UNIQUE NOT NULL,
  password CHARACTER VARYING NOT NULL,
  name CHARACTER VARYING NOT NULL,
  email CHARACTER VARYING NOT NULL,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);